# Railway configuration for Appliance Buddy

[build]
builder = "DOCKERFILE"
# Explicitly tell Railway to use the frontend Dockerfile
dockerfilePath = "frontend.Dockerfile"

[deploy]
# Use the CMD from Dockerfile instead of overriding it
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables will be set in the Railway dashboard