[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node backend/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
NODE_ENV = "production"
PORT = "3001"