# Railway configuration for Appliance Buddy monorepo

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'cd backend && npm start & npm run preview -- --port 3000'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables will be set in the Railway dashboard