# Railway configuration for Appliance Buddy

[build]
builder = "DOCKERFILE"
# Explicitly tell Railway to use the railway.json configuration
dockerfilePath = "Dockerfile"

[deploy]
# Use the CMD from Dockerfile instead of overriding it
# startCommand = "sh -c 'cd backend && npm start & npm run preview -- --host 0.0.0.0 --port 3000'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables will be set in the Railway dashboard